### PR TITLE
2019-10-10 DNC 3.0.0 release

### PR DESCRIPTION
**Pull request by MarkStega**
Update for DNC 3.0.0

I made the ServerSideBlazor project compile but could not get the database setup properly in order to test. CSB Blazor runs as expected (without the glitch in the context that I observed in the other CSB project).

### CODE REVIEW

**Comment by MarkStega** [comment]
I restructured the SSB project to be integral to the same server project (2nd commit)

I messed up with Git so the 3rd & 4th commits cancel each other out

I then changed the names of 3 of the 4 csproj files to not emphasize ClientSideBlazor since the app now supports both CSB & SSB (5th commit)

**Comment by MarkStega** [comment]
Here is a summary of the changes:
1) "Mechanical" changes to move from DNC preview version to release - These were essetially identical to the changes in the role based auth repo. (1st commit)
2) I wasn't a fan of the duplicate code in client side blazor library and the server side web project so I did the following refactoring:
2a) Separated the GUI code that was repeated in the ServerSideBlazor project by first making a copy of ClientSideBlazor.Client and calling it ClientSideBlazor.Blazor.
2b) Removed all GUI code from ClientSideBlazor.Blazor, leaving only Program.cs & Startup.cs
2c) Removed Program.cs, Startup.cs, and Blazor references in the csproj from ClientSideBlazor.Client thus converting it to a razor class library.
2d) Modified Startup.cs in ClientSideBlazor.Server to have some condition compilation based upon the configuration to either host the WASM based ClientSideBlazor.Blazor as CSB or to use ClientSideBlazor.Client as SSB.
2e) Removed the now redundant ServerSideBlazor project. (All of this is in the 2nd commit)
3) Ignore the 3rd & 4th commits, they cancel each other out and essentially really were Git issue related.
4) Finally, realizing that having ClientSideBlazor.xxx projects made no sense when they could be running either CSB or SSB I renamed all of the projects to be BlazorBasedAuth.xxx (5th commit)

**Comment by MarkStega** [comment]
Here is a summary of the changes:

1) "Mechanical" changes to move from DNC preview version to release - These were essentially identical to the changes in the role based auth repo. (1st commit)
2) I wasn't a fan of the duplicate code in the client side blazor library and the server side web project so I did the following refactoring:
    2a) Separated the GUI code that was repeated in the ServerSideBlazor project by first making a copy of ClientSideBlazor.Client and calling it ClientSideBlazor.Blazor.
    2b) Removed all GUI code from ClientSideBlazor.Blazor, leaving only Program.cs & Startup.cs. Startup.cs references the app.razor assembly in ClientSideBlazor.Client.
    2c) Removed Program.cs, Startup.cs, and Blazor references in the csproj from ClientSideBlazor.Client thus converting it to a razor class library.
    2d) Modified Startup.cs in ClientSideBlazor.Server to have some conditional compilation based upon the configuration to either host the WASM based ClientSideBlazor.Blazor as CSB or to use ClientSideBlazor.Client as SSB.
    2e) Removed the now redundant ServerSideBlazor project. (All of this is in the 2nd commit)
3) Ignore the 3rd & 4th commits, they cancel each other out and essentially really were Git issue related.
4) Realizing that having ClientSideBlazor.xxx projects made no sense when they could be running either CSB or SSB I renamed all of the projects to be BlazorBasedAuth.xxx (5th & 6th commits).
5) I found a bug in the SSB implementation that kept the FetchData page from working when there was an 'autologon' from a saved token in local storage. Basically the base address of the http client needed to be set in app.razor rather than AuthService.cs (which, in retrospect, was a poor choice on my part). Anyhow 7th commit.

**Comment by chrissainty** [comment]
Hi Mark, so sorry it's taken me this long to get to these PRs. 

I'll be honest, I'm not sure about the changes you've made. This repo is about providing an easy to follow code sample that mimics the blog post. Code efficiency isn't the goal here - it's allowing people to understand as easily as possible.

I don't think I can accept this PR, I'm really sorry.

**Review by chrissainty — APPROVED** [review]
This is great!

Thank you for the effort you've put into updating this PR. It's much appreciated.

**Pull request merged**
